# **Configure Google Colab Settings**

In [ ]:
#Connect to personal Google Drive space
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#Change directory
%cd /content/
#Create Paths
!mkdir /content/dataset/
!mkdir /content/dataset/linemod/
!mkdir /content/dataset/linemod/Linemod_preprocessed/

/content


In [ ]:
import zipfile
import os
from tqdm import tqdm

zip_path = "/content/drive/MyDrive/Linemod_preprocessed.zip"
extract_to = "/content/dataset/linemod/"

# ایجاد مسیر خروجی اگر وجود ندارد
os.makedirs(extract_to, exist_ok=True)

# باز کردن فایل zip
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # گرفتن لیست فایل‌ها
    file_list = zip_ref.infolist()

    print(f"📦 Extracting {len(file_list)} files...\n")
    for file in tqdm(file_list, desc="Unzipping", unit="file"):
        zip_ref.extract(file, extract_to)

print("\n✅ Extraction complete.")


📦 Extracting 62142 files...



Unzipping: 100%|██████████| 62142/62142 [00:57<00:00, 1076.63file/s] 


✅ Extraction complete.


# **Configure Github Settings**

### Install Git

In [ ]:
#Install/Upgrade Git
!apt-get install git
!apt upgrade git

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.12).
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.12).
Calculating upgrade... Done
The following packages have been kept back:
  libcudnn9-cuda-12 libcudnn9-dev-cuda-12 libldap-2.5-0 libnccl-dev libnccl2
The following packages will be upgraded:
  base-files binutils binutils-common binutils-x86-64-linux-gnu
  cuda-toolkit-12-config-common cuda-toolkit-config-common e2fsprogs
  libbinutils libc-bin libcap2 libctf-nobfd0 libctf0 libext2fs2 libgnutls30
  libpam-modules libpam-modules-bin libpam-runtime libpam0g libperl5.34
  libseccomp2 libss2 libtasn1-6 libudev1 linux-libc-dev logsave openssl perl
  perl-base perl-modules-5.34
29 upgraded, 0 newly installed, 0 to remove and 

### Login

In [ ]:
#Config Git
!git config --global user.email "sina.ghiabi1@gmail.com"
!git config --global user.name "sina-ghiabi"

### Clone project from Github



In [ ]:
%cd /content
!git clone https://github.com/mldl-team/6D-pose-estimation.git

/content
Cloning into '6D-pose-estimation'...
remote: Enumerating objects: 155, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 155 (delta 0), reused 0 (delta 0), pack-reused 153 (from 3)
Receiving objects: 100% (155/155), 205.82 MiB | 14.36 MiB/s, done.
Resolving deltas: 100% (24/24), done.


### Copy modified code into the cloned project

In [ ]:
#Copy the file into cloned project
!cp -r "/content/drive/MyDrive/Backups/6 - Backup/rcvpose" "/content/6D-pose-estimation/Pose Estimation"
!cp -r "/content/drive/MyDrive/Backups/6 - Backup/RCVPose.ipynb" "/content/6D-pose-estimation/Pose Estimation"

### Push the modified project into Github

In [ ]:
#Authentication
!git remote set-url origin https://sina-ghiabi:<SSH>@github.com/mldl-team/6D-pose-estimation.git
!git fetch origin sina
!git checkout sina

#Push the Project into Github
!git add .
!git commit -m "RCVPose-Sixth Version"
!git push origin sina

From https://github.com/mldl-team/6D-pose-estimation
 * branch            sina       -> FETCH_HEAD
Already on 'sina'
Your branch is up to date with 'origin/sina'.
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint: 
hint: 	git submodule add <url> Pose Estimation/rcvpose
hint: 
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint: 
hint: 	git rm --cached Pose Estimation/rcvpose
hint: 
hint: See "git help submodule" for more information.
[sina 7035c30] RCVPose-Sixth Version
 2 files changed, 2 insertions(+)
 create mode 100644 Pose Estimation/RCVPose.ipynb
 create mode 160000 Pose Estimation/rcvpose
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writ

In [ ]:
!ls -l "Pose Estimation/rcvpose"

ls: cannot access 'Pose Estimation/rcvpose': No such file or directory


In [ ]:
# برو به مسیر پروژه (اگر از قبل نرفتی)
%cd /content/6D-pose-estimation/
!ls -l "Pose Estimation/rcvpose"

# حذف احتمالی .git داخلی rcvpose اگر قبلاً submodule بوده
!rm -rf "Pose Estimation/rcvpose/.git"

# حذف مسیر از index گیت (فقط در صورت submodule بودن قبلی)
!git rm --cached -r "Pose Estimation/rcvpose" || echo "rcvpose was not tracked or already clean"

# افزودن همه فایل‌ها از نو
!git add .

# ثبت تغییرات در commit جدید
!git commit -m "Force add Pose Estimation folder with rcvpose subfolder"

# push نهایی به برنچ sina
!git push origin sina


/content/6D-pose-estimation
ls: cannot access 'Pose Estimation/rcvpose': No such file or directory
fatal: pathspec 'Pose Estimation/rcvpose' did not match any files
rcvpose was not tracked or already clean
On branch sina
Your branch is up to date with 'origin/sina'.

nothing to commit, working tree clean
Everything up-to-date


# **Configure Wandb Settings**

In [ ]:
#Wandb installation
!pip install wandb

In [ ]:
!wandb login

wandb: WARNING Using legacy-service, which is deprecated. If this is unintentional, you can fix it by ensuring you do not call `wandb.require('legacy-service')` and do not set the WANDB_X_REQUIRE_LEGACY_SERVICE environment variable.
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit: 
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: sina-ghiabi (erythm-mldl) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin


In [ ]:
import random

import wandb

# Start a new wandb run to track this script.
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="erythm-mldl",
    # Set the wandb project where this run will be logged.
    project="6D",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.02,
        "architecture": "CNN",
        "dataset": "CIFAR-100",
        "epochs": 10,
    },
)

# Simulate training.
epochs = 10
offset = random.random() / 5
for epoch in range(2, epochs):
    acc = 1 - 2**-epoch - random.random() / epoch - offset
    loss = 2**-epoch + random.random() / epoch + offset

    # Log metrics to wandb.
    run.log({"acc": acc, "loss": loss})

# Finish the run and upload any remaining data.
run.finish()

wandb: Currently logged in as: sina-ghiabi (erythm-mldl) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin


# **Configure Python**

In [ ]:
#Install Python
!pip install ipython

#Usage of the library is to display input or output images
from IPython.display import Image, display

# **Configure PyTorch**

In [ ]:
#Install PyTorch
!pip install torch
!pip install torch torchvision opencv-python matplotlib tqdm pyyaml
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

#Usage of the library is the primary neural network computation framework.
import torch
torch.__version__

Looking in indexes: https://download.pytorch.org/whl/cu118


'2.6.0+cu124'

# **Configure YOLO**

In [ ]:
#Usage of the library is To run Object Detection & Image Classification with YOLO
!pip install ultralytics

#Check availability of ultralytics
!ultralytics.checks()

import ultralytics

from ultralytics import YOLO

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 24.5 MB/s eta 0:00:00
/bin/bash: -c: line 2: syntax error: unexpected end of file
Creating new Ultralytics Settings v0.0.6 file ✅ 
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.


# **Configure OpenCV**

In [ ]:
#Usage of the library is for real‐time image and video processing
!pip install opencv-python

import cv2

In [ ]:
#Check if we have an access to nvidia
#If "/bin/bash: line 1: nvidia-smi: command not found" appeared, change Runtime to GPU
!nvidia-smi

Thu May 22 16:19:03 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

# **Configure Open3D**
### **Open3D is used for 3D geometry processing in Pose Estimation, SciPy for scientific computations**

In [ ]:
!pip install open3d scipy numpy
!pip install opencv-python tensorboard pyyaml scipy scikit-image
!pip install tensorboardX

import open3d as o3d
from scipy.spatial import distance_matrix
import numpy as np

### **Manage file paths with os Library**

In [ ]:
import os
import glob

#Examples
#img_path = os.path.join('data', 'images', img_name)
#images = glob.glob('data/images/*.jpg')
#labels = glob.glob('data/labels/*.txt')

### **Progress Bar**

In [ ]:
!pip install tqdm
from tqdm import tqdm

# **Object Detection**


### **Import all the Tools**

In [ ]:
import torch
import matplotlib.pyplot as plt
import cv2
import numpy as np
from ultralytics import YOLO

#Choose YOLO Model
model = YOLO('yolov8s.pt')
#Choose Computing Device - CUDA: Compute Unified Device Architecture
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
#Transfer Model to Computing Device
model.to(device)

100%|██████████| 21.5M/21.5M [00:00<00:00, 140MB/s] 


YOLO(
  (model): DetectionModel(
    (model): Sequential(
      (0): Conv(
        (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): C2f(
        (cv1): Conv(
          (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(96, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_s

### **Make Dataset Ready**

In [ ]:
import os
import yaml
import random
import shutil
from PIL import Image
from collections import defaultdict, Counter
from tqdm import tqdm

# ================== CONFIGURATION ======================
!mkdir /content/dataset/linemod/Linemod_ready
root_dir = '/content/dataset/linemod/Linemod_preprocessed/data'
output_base = '/content/dataset/linemod/Linemod_ready'  # Base output folder
img_out_train = os.path.join(output_base, 'images/train')
img_out_val = os.path.join(output_base, 'images/val')
label_out_train = os.path.join(output_base, 'labels/train')
label_out_val = os.path.join(output_base, 'labels/val')

# Create directories if they don't exist
for path in [img_out_train, img_out_val, label_out_train, label_out_val]:
    os.makedirs(path, exist_ok=True)

# Define valid class IDs and their YOLO-mapped indices (0-based)
existing_classes = [1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15]
#Create {cls_id: idx}: {0:1} - {1:2} - {2:4} - {3:5} ...
class_map = {cls_id: idx for idx, cls_id in enumerate(existing_classes)}

# ================ STEP 1: GATHER SAMPLES ===================
samples_by_class = defaultdict(list)
for cls in existing_classes:
    folder_path = os.path.join(root_dir, f"{cls:02d}")
    rgb_folder = os.path.join(folder_path, 'rgb')
    gt_file = os.path.join(folder_path, 'gt.yml')

    if not os.path.exists(gt_file):
        print(f"⚠️ Class {cls:02d} missing → skipped.")
        continue

    with open(gt_file, 'r') as f:
        gt_data = yaml.safe_load(f)

    for img_id in gt_data:
        img_path = os.path.join(rgb_folder, f"{int(img_id):04d}.png")
        if os.path.exists(img_path):
            samples_by_class[cls].append(img_id)

# Display class distribution
print("🔍 Class distribution:")
for cls, samples in samples_by_class.items():
    print(f"Class {cls:>2}: {len(samples)} samples")

# =============== STEP 2: LABEL AND IMAGE PROCESSING =================
def save_yolo_labels(sample_list, mode, cls, gt_data, rgb_folder):
    label_dir = label_out_train if mode == 'train' else label_out_val
    img_dir = img_out_train if mode == 'train' else img_out_val
    label_id = class_map[cls]

    for img_id in sample_list:
        img_path = os.path.join(rgb_folder, f"{int(img_id):04d}.png")
        img = Image.open(img_path)
        w, h = img.size

        bbox = gt_data[img_id][0]['obj_bb']
        x, y, bw, bh = bbox
        x_center = (x + bw / 2) / w
        y_center = (y + bh / 2) / h
        norm_bw = bw / w
        norm_bh = bh / h

        # Save label
        label_file = f"{cls:02d}_{int(img_id):04d}.txt"
        with open(os.path.join(label_dir, label_file), 'w') as f:
            f.write(f"{label_id} {x_center:.6f} {y_center:.6f} {norm_bw:.6f} {norm_bh:.6f}\n")

        # Save image
        img_out_path = os.path.join(img_dir, f"{cls:02d}_{int(img_id):04d}.png")
        shutil.copy(img_path, img_out_path)

# Split, save labels and copy images
print("\n⚙️ Processing and splitting images...")
for cls, samples in samples_by_class.items():
    random.shuffle(samples)
    split_idx = int(0.8 * len(samples))
    train_samples = samples[:split_idx]
    val_samples = samples[split_idx:]

    folder_path = os.path.join(root_dir, f"{cls:02d}")
    rgb_folder = os.path.join(folder_path, 'rgb')
    gt_file = os.path.join(folder_path, 'gt.yml')

    with open(gt_file, 'r') as f:
        gt_data = yaml.safe_load(f)

    save_yolo_labels(train_samples, 'train', cls, gt_data, rgb_folder)
    save_yolo_labels(val_samples, 'val', cls, gt_data, rgb_folder)

# ============= STEP 3: LABEL DISTRIBUTION STATS ===============
def count_labels(label_dir):
    counter = Counter()
    for filename in os.listdir(label_dir):
        if filename.endswith('.txt'):
            with open(os.path.join(label_dir, filename), 'r') as f:
                for line in f:
                    class_id = int(line.strip().split()[0])
                    counter[class_id] += 1
    return counter

train_counts = count_labels(label_out_train)
val_counts = count_labels(label_out_val)

import pandas as pd
df_stats = pd.DataFrame({
    "Train Count": pd.Series(train_counts),
    "Validation Count": pd.Series(val_counts)
}).fillna(0).astype(int)

print(df_stats)

print("✅ YOLO dataset generated, split, and labeled.")

🔍 Class distribution:
Class  1: 1236 samples
Class  2: 1214 samples
Class  4: 1201 samples
Class  5: 1196 samples
Class  6: 1179 samples
Class  8: 1188 samples
Class  9: 1254 samples
Class 10: 1253 samples
Class 11: 1220 samples
Class 12: 1237 samples
Class 13: 1152 samples
Class 14: 1227 samples
Class 15: 1243 samples

⚙️ Processing and splitting images...
    Train Count  Validation Count
0           988               248
1           971               243
2           960               241
3           956               240
4           943               236
5           950               238
6          1003               251
7          1002               251
8           976               244
9           989               248
10          921               231
11          981               246
12          994               249
✅ YOLO dataset generated, split, and labeled.


### **Train the Model**

In [ ]:
model.train(
    data='/content/project/6D-pose-estimation/configs/linemod_final.yaml',
    epochs=15,
    imgsz=640,
    batch=8,
    device=0,
    patience=5,
    weight_decay=0.0005
)

In [ ]:
!cp -r runs/detect/train ~/6d/yolo_logs/

### **Save Trained Model Metrics**

In [ ]:
from ultralytics import YOLO

model = YOLO("model.pt")
metrics = model.val(data="linemod_final.yaml", plots=True, save=True)

# **Pose Estimation**

### Clone RCVPose from Github

In [ ]:
#Create Directory for RCVPose Estimation Tool
%cd /content
!git clone https://github.com/aaronWool/rcvpose.git

/content
Cloning into 'rcvpose'...
remote: Enumerating objects: 1556, done.
remote: Counting objects: 100% (121/121), done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 1556 (delta 47), reused 98 (delta 36), pack-reused 1435 (from 1)
Receiving objects: 100% (1556/1556), 17.51 MiB | 42.68 MiB/s, done.
Resolving deltas: 100% (679/679), done.


### **Prepare File & Folders for RCVPose**

### 1 - Move Objects' Models From models Folder To Class Folders & Rename Them To mesh.ply

In [ ]:
import os
import shutil

# ==== CONFIGURATION ====
# Base directory for preprocessed model data
data_path = "/content/dataset/linemod/Linemod_preprocessed/data"
# Directory containing original model files
models_path = "/content/dataset/linemod/Linemod_preprocessed/models"

for filename in os.listdir(models_path):
    # Only process files matching the pattern obj_<id>.ply
    if not filename.startswith("obj_") or not filename.endswith(".ply"):
        continue

    # Extract the model identifier (e.g., "01")
    model_id = filename.split("_")[1].split(".")[0]  # example: "01"
    src_file = os.path.join(models_path, filename)
    dst_folder = os.path.join(data_path, model_id)

    # Skip if the destination folder does not exist
    if not os.path.isdir(dst_folder):
        print(f"Folder {model_id} does not exist → skipped")
        continue

    # Copy and rename the model file to mesh.ply
    dst_file = os.path.join(dst_folder, "mesh.ply")
    print(f"Copying {filename} → {dst_file}")
    shutil.copy2(src_file, dst_file)

print("\n✅ Model files have been moved and renamed to mesh.ply.")


Copying obj_13.ply → /content/dataset/linemod/Linemod_preprocessed/data/13/mesh.ply
Folder 03 does not exist → skipped
Copying obj_10.ply → /content/dataset/linemod/Linemod_preprocessed/data/10/mesh.ply
Copying obj_15.ply → /content/dataset/linemod/Linemod_preprocessed/data/15/mesh.ply
Copying obj_12.ply → /content/dataset/linemod/Linemod_preprocessed/data/12/mesh.ply
Copying obj_05.ply → /content/dataset/linemod/Linemod_preprocessed/data/05/mesh.ply
Copying obj_11.ply → /content/dataset/linemod/Linemod_preprocessed/data/11/mesh.ply
Folder 07 does not exist → skipped
Copying obj_14.ply → /content/dataset/linemod/Linemod_preprocessed/data/14/mesh.ply
Copying obj_01.ply → /content/dataset/linemod/Linemod_preprocessed/data/01/mesh.ply
Copying obj_08.ply → /content/dataset/linemod/Linemod_preprocessed/data/08/mesh.ply
Copying obj_04.ply → /content/dataset/linemod/Linemod_preprocessed/data/04/mesh.ply
Copying obj_02.ply → /content/dataset/linemod/Linemod_preprocessed/data/02/mesh.ply
Copyin

### 2 - Create Outside9.npy From Objects' Models
A NumPy file containing a [9, 3] array of 3D keypoint coordinates sampled from the object mesh using Farthest-Point Sampling. These five points are chosen to maximally span the surface of the model. During data preprocessing, each keypoint is used to generate a per-frame radial distance map: for every pixel with valid depth, its Euclidean distance in 3D space to each keypoint is computed and stored. These distance maps serve as ground-truth supervision when training a network to predict 3D distance fields from RGB-D inputs.


In [ ]:
import os
import numpy as np
import open3d as o3d

def fps(points: np.ndarray, k: int, seed: int = 0) -> np.ndarray:
    """
    Farthest-Point Sampling:
      - points: (N,3) array of XYZ samples
      - k: number of keypoints to pick
    Returns an array of shape (k,3).
    """
    np.random.seed(seed)
    N = points.shape[0]
    centroids = np.zeros((k,), dtype=np.int32)
    distances = np.full((N,), np.inf)
    farthest = np.random.randint(0, N)
    for i in range(k):
        centroids[i] = farthest
        centroid = points[farthest]
        dist = np.sum((points - centroid)**2, axis=1)
        distances = np.minimum(distances, dist)
        farthest = np.argmax(distances)
    return points[centroids]

# --- Define base path and class list ---
base_dir = "/content/dataset/linemod/Linemod_preprocessed/data"
classes = ['01','02','04','05','06','08','09','10','11','12','13','14','15']

for cls in classes:
    seq_dir = os.path.join(base_dir, cls)
    mesh_path = os.path.join(seq_dir, "mesh.ply")

    if not os.path.isfile(mesh_path):
        print(f"⚠️  Skipping {cls}: mesh.ply not found at {mesh_path}")
        continue

    print(f"🎯 Processing class {cls}")

    # Load point cloud
    pcd = o3d.io.read_point_cloud(mesh_path)
    pts = np.asarray(pcd.points)

    if pts.shape[0] < 9:
        print(f"❌ Not enough points in {mesh_path} (only {pts.shape[0]}), skipping.")
        continue

    # Perform Farthest-Point Sampling
    keypoints = fps(pts, k=9, seed=42)

    # Save output
    out_path = os.path.join(seq_dir, "Outside9.npy")
    np.save(out_path, keypoints)
    print(f"✅ Saved {out_path} (shape {keypoints.shape})")

    # Test load to confirm file is valid
    try:
        test = np.load(out_path)
        print(f"📦 Verified file: {out_path} loaded successfully with shape {test.shape}\n")
    except Exception as e:
        print(f"❌ Failed to load saved file: {e}\n")


🎯 Processing class 01
✅ Saved /content/dataset/linemod/Linemod_preprocessed/data/01/Outside9.npy (shape (9, 3))
📦 Verified file: /content/dataset/linemod/Linemod_preprocessed/data/01/Outside9.npy loaded successfully with shape (9, 3)

🎯 Processing class 02
✅ Saved /content/dataset/linemod/Linemod_preprocessed/data/02/Outside9.npy (shape (9, 3))
📦 Verified file: /content/dataset/linemod/Linemod_preprocessed/data/02/Outside9.npy loaded successfully with shape (9, 3)

🎯 Processing class 04
✅ Saved /content/dataset/linemod/Linemod_preprocessed/data/04/Outside9.npy (shape (9, 3))
📦 Verified file: /content/dataset/linemod/Linemod_preprocessed/data/04/Outside9.npy loaded successfully with shape (9, 3)

🎯 Processing class 05
✅ Saved /content/dataset/linemod/Linemod_preprocessed/data/05/Outside9.npy (shape (9, 3))
📦 Verified file: /content/dataset/linemod/Linemod_preprocessed/data/05/Outside9.npy loaded successfully with shape (9, 3)

🎯 Processing class 06
✅ Saved /content/dataset/linemod/Linem

### It is only Possible to see the content of Outside9.npy using code below

In [ ]:
import numpy as np
import os

base_path = "/content/dataset/linemod/Linemod_preprocessed/data"

# لیست کلاس‌ها از 01 تا 15 (بدون 03 و 07 چون معمولاً در Linemod نیستند)
classes = ['01','02','04','05','06','08','09','10','11','12','13','14','15']

for cls in classes:
    file_path = os.path.join(base_path, cls, "Outside9.npy")

    if not os.path.isfile(file_path):
        print(f"⚠️ File not found for class {cls}: {file_path}")
        continue

    print(f"📂 Class {cls}'s Outside9.npy:")
    data = np.load(file_path)
    print(data, "\n")


📂 Class 01's Outside9.npy:
[[-20.3664  19.3442  -7.6361]
 [ 35.6255 -16.9712 -44.263 ]
 [  7.5111  -4.4303  41.4566]
 [ -1.604  -33.9459  -5.4867]
 [-26.6571 -13.9838 -43.0416]
 [ 10.2731  20.1762 -40.7712]
 [ 13.9023  17.8718   9.8713]
 [-20.7606  -9.8099  16.1704]
 [ 30.0282 -21.3168 -10.4571]] 

📂 Class 02's Outside9.npy:
[[  12.3025  -17.8971   43.9721]
 [  90.5719   -1.9537 -107.092 ]
 [ -70.8535   22.383   -92.6023]
 [  53.2234   58.4881  -23.509 ]
 [   7.5829  -29.9273  -56.5234]
 [ -92.0255   -4.1247   -3.2999]
 [  66.5464    0.135   107.388 ]
 [  86.4643  -24.3331  -25.008 ]
 [ -11.3591   30.5359   -5.3499]] 

📂 Class 04's Outside9.npy:
[[-60.7914  62.0638 -19.3466]
 [ 67.0034 -10.3907  -2.8697]
 [-54.8219 -67.9932  19.5177]
 [-10.7869  13.9897  49.5203]
 [-19.0693 -15.506  -47.6997]
 [ 17.4433  49.3472 -20.1936]
 [-66.316   -0.8159   7.7016]
 [  4.4803 -41.5652  16.038 ]
 [-56.6145 -67.7992 -45.8652]] 

📂 Class 05's Outside9.npy:
[[ -8.0273  55.7049 -79.5385]
 [  1.2705   6.3

### **3 - Generate Pose For Each Picture Using gt.yml**

Purpose: This script generates pose files (Rotation & Translation matrices) for each image in the dataset.

How it works:
1. Reads the depth image and removes the background using the mask.
2. Converts the depth into a point cloud (scene point cloud).
3. Loads the 3D model (`mesh.ply`) and samples it into a point cloud.
4. Uses ICP to align the model point cloud with the scene point cloud.
5. Saves the resulting [R|t] matrix as a `.npy` file named `poseXXXXXX.npy`.

Output:
Each frame will have a file like `pose000123.npy` in the `pose/` folder.
It contains a 3×4 RT matrix with:
- R: rotation (3×3)
- t: translation (3×1)

Use in RCVPose:
These pose files are used to:
- Project 3D keypoints onto 2D image space
- Generate 3D radius maps
- Serve as ground truth during training

Requirements:
- `.dpt` depth images
- `.png` binary masks
- 3D model in `.ply` format
- Camera intrinsics `K`


In [ ]:
import os
import numpy as np
import yaml
from tqdm import tqdm

# مسیر اصلی دیتاست
base_root = "/content/dataset/linemod/Linemod_preprocessed/data"
class_ids = ['01', '02', '04', '05', '06', '08', '09', '10', '11', '12', '13', '14', '15']

for class_id in class_ids:
    print(f"\n📂 Processing class {class_id}...")
    class_path = os.path.join(base_root, class_id)
    gt_path = os.path.join(class_path, "gt.yml")
    pose_dir = os.path.join(class_path, "pose")

    if not os.path.exists(gt_path):
        print(f"⚠️ gt.yml not found for class {class_id} — skipped.")
        continue

    if not os.path.exists(pose_dir):
        os.makedirs(pose_dir)

    with open(gt_path, 'r') as f:
        gt_data = yaml.safe_load(f)

    for img_id, pose_list in tqdm(gt_data.items(), desc=f"Class {class_id}", unit="image"):
        idx = int(img_id)
        if len(pose_list) > 1:
            print(f"⚠️ Multiple objects in image {idx:06d}, using only the first one.")

        pose = pose_list[0]
        R = np.array(pose['cam_R_m2c'], dtype=np.float32).reshape(3, 3)
        t = np.array(pose['cam_t_m2c'], dtype=np.float32).reshape(3, 1)  # mm

        # خروجی: ماتریس 3×4 به شکل [R | t]
        RT = np.hstack([R, t])
        save_path = os.path.join(pose_dir, f"pose{idx:06d}.npy")
        np.save(save_path, RT)

print("\n✅ All poses extracted and saved from gt.yml files.")


📂 Processing class 01...


Class 01: 100%|██████████| 1236/1236 [00:00<00:00, 10811.26image/s]



📂 Processing class 02...


Class 02: 100%|██████████| 1214/1214 [00:00<00:00, 9909.30image/s] 


⚠️ Multiple objects in image 000000, using only the first one.
⚠️ Multiple objects in image 000001, using only the first one.
⚠️ Multiple objects in image 000002, using only the first one.
⚠️ Multiple objects in image 000003, using only the first one.
⚠️ Multiple objects in image 000004, using only the first one.
⚠️ Multiple objects in image 000005, using only the first one.
⚠️ Multiple objects in image 000006, using only the first one.
⚠️ Multiple objects in image 000007, using only the first one.
⚠️ Multiple objects in image 000008, using only the first one.
⚠️ Multiple objects in image 000009, using only the first one.
⚠️ Multiple objects in image 000010, using only the first one.
⚠️ Multiple objects in image 000011, using only the first one.
⚠️ Multiple objects in image 000012, using only the first one.
⚠️ Multiple objects in image 000013, using only the first one.
⚠️ Multiple objects in image 000014, using only the first one.
⚠️ Multiple objects in image 000015, using only the fir

Class 04:  79%|███████▊  | 943/1201 [00:00<00:00, 9811.03image/s]


KeyboardInterrupt: 

### 4 - Modify RGB, Mask, Depth Files Format From 4 Digits to 6 Digits - Radius Map Needs Files in 6-Digit Format

In [ ]:
from tqdm import tqdm
import os

def rename_files_to_6_digit(base_dir, classes):
    for cls in classes:
        print(f"\n🔧 Renaming files in class {cls} ...")

        for folder_name in ['rgb','mask', 'depth']:
            folder_path = os.path.join(base_dir, cls, folder_name)
            if not os.path.isdir(folder_path):
                print(f"⚠️ Skipping {cls}/{folder_name}: folder not found.")
                continue

            file_list = [f for f in os.listdir(folder_path) if os.path.splitext(f)[0].isdigit()]
            for fname in tqdm(file_list, desc=f"{cls}/{folder_name}", unit="file"):
                name, ext = os.path.splitext(fname)
                idx = int(name)
                new_name = f"{idx:06d}{ext}"
                src = os.path.join(folder_path, fname)
                dst = os.path.join(folder_path, new_name)
                os.rename(src, dst)

    print("\n✅ All depth and mask files renamed to 6-digit format.")

# === Set base path and class list ===
base_dir = "/content/dataset/linemod/Linemod_preprocessed/data"
classes = ['01','02','04','05','06','08','09','10','11','12','13','14','15']

rename_files_to_6_digit(base_dir, classes)



🔧 Renaming files in class 01 ...


01/depth: 100%|██████████| 1236/1236 [00:00<00:00, 50789.24file/s]



🔧 Renaming files in class 02 ...


02/depth: 100%|██████████| 1214/1214 [00:00<00:00, 51001.47file/s]



🔧 Renaming files in class 04 ...


04/depth: 100%|██████████| 1201/1201 [00:00<00:00, 49928.23file/s]



🔧 Renaming files in class 05 ...


05/depth: 100%|██████████| 1196/1196 [00:00<00:00, 48937.50file/s]



🔧 Renaming files in class 06 ...


06/depth: 100%|██████████| 1179/1179 [00:00<00:00, 49069.09file/s]



🔧 Renaming files in class 08 ...


08/depth: 100%|██████████| 1188/1188 [00:00<00:00, 50308.27file/s]



🔧 Renaming files in class 09 ...


09/depth: 100%|██████████| 1254/1254 [00:00<00:00, 51050.26file/s]



🔧 Renaming files in class 10 ...


10/depth: 100%|██████████| 1253/1253 [00:00<00:00, 49937.88file/s]



🔧 Renaming files in class 11 ...


11/depth: 100%|██████████| 1220/1220 [00:00<00:00, 50958.01file/s]



🔧 Renaming files in class 12 ...


12/depth: 100%|██████████| 1237/1237 [00:00<00:00, 49087.98file/s]



🔧 Renaming files in class 13 ...


13/depth: 100%|██████████| 1152/1152 [00:00<00:00, 49530.90file/s]



🔧 Renaming files in class 14 ...


14/depth: 100%|██████████| 1227/1227 [00:00<00:00, 50832.27file/s]



🔧 Renaming files in class 15 ...


15/depth: 100%|██████████| 1243/1243 [00:00<00:00, 49504.06file/s]


✅ All depth and mask files renamed to 6-digit format.


###5 -  Convert Depth files from .png to .dpt - Radius Map Needs Depth Files With .dpt Format

In [ ]:
import os
import numpy as np
from PIL import Image
import struct

def save_dpt_file(png_path, dpt_path, scale=1.0):
    """
    Converts a depth .png file to a .dpt file with proper binary format:
    [uint32 height][uint32 width][uint16 depth values]
    Then deletes the original .png file.
    """
    depth_img = np.array(Image.open(png_path)).astype(np.float32)
    depth_img = (depth_img * scale).astype(np.uint16)

    h, w = depth_img.shape

    with open(dpt_path, 'wb') as f:
        f.write(struct.pack('I', h))
        f.write(struct.pack('I', w))
        f.write(depth_img.tobytes())

    # Delete the original .png file after successful conversion
    os.remove(png_path)

def convert_all_png_to_dpt_in_classes(base_dir, classes, scale=1.0):
    """
    Processes all PNG files in the 'depth' folder of each class and creates corresponding .dpt files.
    """
    for cls in classes:
        depth_dir = os.path.join(base_dir, cls, "depth")
        if not os.path.exists(depth_dir):
            print(f"⚠️ Skipping class {cls}: no depth folder found.")
            continue

        print(f"\n🔍 Processing class {cls}...")

        png_files = sorted([f for f in os.listdir(depth_dir) if f.endswith(".png")])
        for fname in tqdm(png_files, desc=f"Class {cls}", unit="file"):
            png_path = os.path.join(depth_dir, fname)
            dpt_path = os.path.join(depth_dir, os.path.splitext(fname)[0] + ".dpt")
            save_dpt_file(png_path, dpt_path, scale)

    print("\n✅ All PNG files have been converted to .dpt format.")

# === Base dataset path and class list ===
base_dir = "/content/dataset/linemod/Linemod_preprocessed/data"
classes = ['01','02','04','05','06','08','09','10','11','12','13','14','15']

# PNG values are already in mm → no scaling needed
scale = 1.0

convert_all_png_to_dpt_in_classes(base_dir, classes, scale)



🔍 Processing class 01...


Class 01: 100%|██████████| 1236/1236 [00:04<00:00, 304.16file/s]



🔍 Processing class 02...


Class 02:  62%|██████▏   | 748/1214 [00:02<00:01, 298.38file/s]


KeyboardInterrupt: 

### 3 - Generate Radius Map

We compute the mesh and keypoints to:

* Mesh, accurately represent an object’s 3D shape.
* Reduce complexity by sampling a few representative points.
* Enable fast registration and matching across views.
* Support precise pose estimation via 3D–2D point correspondences.
* Improve efficiency in real-time or learning-based applications.


### **Generate Radius Map**

In [ ]:
!python3 /content/rcvpose/3DRadius_lm.py

Streaming output truncated to the last 5000 lines.
📏 Out_pt5_dm | 001200.dpt | Max dist (mm): 97.02337410825437
📏 Out_pt5_dm | 000415.dpt | Max dist (mm): 115.52209684108925
📏 Out_pt5_dm | 001168.dpt | Max dist (mm): 92.01717892087484
📏 Out_pt5_dm | 000279.dpt | Max dist (mm): 92.28458812229805
📏 Out_pt5_dm | 000587.dpt | Max dist (mm): 119.30294791698198
📏 Out_pt5_dm | 000868.dpt | Max dist (mm): 203.82829914913512
📏 Out_pt5_dm | 001129.dpt | Max dist (mm): 103.13277375114677
📏 Out_pt5_dm | 001128.dpt | Max dist (mm): 116.61377785807093
📏 Out_pt5_dm | 000074.dpt | Max dist (mm): 90.44984844670785
📏 Out_pt5_dm | 000421.dpt | Max dist (mm): 138.57407777595685
📏 Out_pt5_dm | 000519.dpt | Max dist (mm): 110.48427149640798
📏 Out_pt5_dm | 000296.dpt | Max dist (mm): 97.48612944136423
📏 Out_pt5_dm | 000738.dpt | Max dist (mm): 99.42952083308575
📏 Out_pt5_dm | 000253.dpt | Max dist (mm): 92.95488491251758
📏 Out_pt5_dm | 000025.dpt | Max dist (mm): 85.80252293087777
📏 Out_pt5_dm | 000727.dpt |

### **Train Model**

### Split Data: %70: Train - %20 Validation - %10 Test

In [ ]:
#Split RGB Files to Train Validate Test
import os
import glob
import yaml
import random

# ==== CONFIGURATION ====
# Base directory containing class subfolders
base_dir = "/content/dataset/linemod/Linemod_preprocessed/data"
# List of class identifiers to process
classes = ["01","02","04","05","06","08","09","10","11","12","13","14","15"]
# Fixed seed for reproducibility in splitting
random.seed(42)

for cls in classes:
    print(f"\n--- Splitting RGB frames for class {cls} ---")

    # 1) Gather all RGB image indices (filenames without extension)
    rgb_dir = os.path.join(base_dir, cls, "rgb")
    rgb_paths = sorted(glob.glob(os.path.join(rgb_dir, "*.png")))
    rgb_idx = [os.path.splitext(os.path.basename(p))[0] for p in rgb_paths]

    # 2) Load GT keys from gt.yml, zero-pad them to six digits
    gt_path = os.path.join(base_dir, cls, "gt.yml")
    if not os.path.isfile(gt_path):
        print(f"WARNING: gt.yml not found for class {cls}, skipping.")
        continue

    with open(gt_path, "r") as f:
        gt = yaml.safe_load(f)
    gt_keys = {f"{int(k):06d}" for k in gt.keys()}

    # 3) Keep only indices present in both RGB and GT
    valid_idx = [i for i in rgb_idx if i in gt_keys]
    if not valid_idx:
        print(f"WARNING: No valid frames for class {cls}, skipping.")
        continue

    # 4) Shuffle and split 70% train / 20% val / 10% test
    random.shuffle(valid_idx)
    n = len(valid_idx)
    cut1 = int(0.7 * n)
    cut2 = int(0.9 * n)
    train_idx = valid_idx[:cut1]
    val_idx   = valid_idx[cut1:cut2]
    test_idx  = valid_idx[cut2:]

    # 5) Write splits to text files under a new "Split" folder
    split_dir = os.path.join(base_dir, cls, "Split")
    os.makedirs(split_dir, exist_ok=True)
    with open(os.path.join(split_dir, "train.txt"), "w") as f:
        f.write("\n".join(train_idx))
    with open(os.path.join(split_dir, "val.txt"), "w") as f:
        f.write("\n".join(val_idx))
    with open(os.path.join(split_dir, "test.txt"), "w") as f:
        f.write("\n".join(test_idx))

    print(f"✅ Class {cls}: train={len(train_idx)}, val={len(val_idx)}, test={len(test_idx)}")

print("\nAll classes processed successfully.")



--- Splitting RGB frames for class 01 ---
✅ Class 01: train=865, val=247, test=124

--- Splitting RGB frames for class 02 ---
✅ Class 02: train=849, val=243, test=122

--- Splitting RGB frames for class 04 ---
✅ Class 04: train=840, val=240, test=121

--- Splitting RGB frames for class 05 ---
✅ Class 05: train=837, val=239, test=120

--- Splitting RGB frames for class 06 ---
✅ Class 06: train=825, val=236, test=118

--- Splitting RGB frames for class 08 ---
✅ Class 08: train=831, val=238, test=119

--- Splitting RGB frames for class 09 ---


KeyboardInterrupt: 

In [ ]:
# @title Normalize and overwrite dataset files in-place
import os
import numpy as np
from PIL import Image

# Parameters
ROOT        = "/content/dataset/linemod/Linemod_preprocessed/data"
CLASSES     = sorted([d for d in os.listdir(ROOT) if os.path.isdir(os.path.join(ROOT, d))])
OUT_PTS     = [f"Out_pt{i}_dm" for i in range(1,10)]
MEAN_RGB    = np.array([0.485, 0.456, 0.406], dtype=np.float32)
STD_RGB     = np.array([0.229, 0.224, 0.225], dtype=np.float32)
DEPTH_MAX   = 10.0

def read_depth_dpt(path):
    with open(path, "rb") as f:
        h, w = np.fromfile(f, dtype=np.uint32, count=2)
        data = np.fromfile(f, dtype=np.uint16, count=h*w)
    return data.reshape(h, w).astype(np.float32)

for cls in CLASSES:
    cls_dir = os.path.join(ROOT, cls)
    print(f"Processing class {cls}…")
    # ---- normalize Out_ptX_dm/*.npy ----
    for out_dir in OUT_PTS:
        full_out = os.path.join(cls_dir, out_dir)
        if not os.path.isdir(full_out):
            continue
        for fname in os.listdir(full_out):
            if not fname.endswith(".npy"):
                continue
            path = os.path.join(full_out, fname)
            arr  = np.load(path).astype(np.float32)
            m = arr.max() if arr.max()>0 else 1.0
            arr_norm = arr / m
            np.save(path, arr_norm)
    # ---- normalize rgb, depth, mask, pose ----
    # find all image ids from Split/train.txt
    split = os.path.join(cls_dir, "Split", "train.txt")
    if not os.path.isfile(split):
        split = os.path.join(cls_dir, "Split", "val.txt")
    ids = [l.strip() for l in open(split).readlines()]
    for img_id in ids:
        idx = int(img_id)
        # rgb
        rgb_p  = os.path.join(cls_dir, "rgb",   f"{idx:06d}.png")
        im     = np.asarray(Image.open(rgb_p).convert("RGB"), dtype=np.float32) / 255.0
        im     = (im - MEAN_RGB[None,None,:]) / STD_RGB[None,None,:]
        np.save(rgb_p.replace(".png", ".npy"), im)
        # depth
        dp_p   = os.path.join(cls_dir, "depth", f"{idx:06d}.dpt")
        dp     = read_depth_dpt(dp_p)
        dp     = np.clip(dp, 0, DEPTH_MAX) / DEPTH_MAX
        np.save(dp_p.replace(".dpt", ".npy"), dp)
        # mask
        ms_p   = os.path.join(cls_dir, "mask",  f"{idx:06d}.png")
        ms     = np.asarray(Image.open(ms_p).convert("L"), dtype=np.uint8)
        ms_bin = (ms>0).astype(np.float32)
        np.save(ms_p.replace(".png", ".npy"), ms_bin)
        # pose
        p_p    = os.path.join(cls_dir, "pose",  f"pose{idx:06d}.npy")
        pose   = np.load(p_p).astype(np.float32)
        # optionally normalize translation by 1000 (meters→mm)
        pose[:3,3] /= 1000.0
        np.save(p_p, pose)

print("Normalization complete. Overwritten .npy files alongside originals.")


Processing class 01…
Processing class 02…


FileNotFoundError: [Errno 2] No such file or directory: '/content/dataset/linemod/Linemod_preprocessed/data/02/depth/000848.dpt'

In [ ]:
!python /content/rcvpose/main.py \
--mode train \
--class_name 01 \
--kpt_num 7 \
--root_dataset "/content/dataset/linemod/Linemod_preprocessed" \
--batch_size 8 \
--initial_lr 1e-4
# 9 Keypoints from (0 - 8) + 1 Core = 7

Output logs:  logs/lm/01Kp7
No kpt file found, generating kpts...
No kpt file found, generating kpts...
Using 1 GPU
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.0001
    maximize: False
    weight_decay: 0
)
Train epoch=0:   0%|                                     | 0/31 [00:00<?, ?it/s]NaN or Inf found in input tensor.

Train epoch=0:   3%|▉                            | 1/31 [00:03<01:36,  3.23s/it]NaN or Inf found in input tensor.

Train epoch=0:  10%|██▊                          | 3/31 [00:04<00:40,  1.43s/it]NaN or Inf found in input tensor.

Train epoch=0:  13%|███▋                         | 4/31 [00:06<00:39,  1.47s/it]NaN or Inf found in input tensor.

Train epoch=0:  16%|████▋                        | 5/31 [00:07<00:38,  1.49s/it]NaN or Inf found in input tensor.

Train epoch=0:  19%|█████▌                       | 6/31 [00:09<00:37,  1.51s/it]NaN or 

In [ ]:
!python /content/rcvpose/main.py \
  --mode test \
  --dataset lm \
  --class_name 01 \
  --kpt_num 7 \
  --root_dataset "/content/dataset/linemod/Linemod_preprocessed" \
  --batch_size 8 \
  --model_dir "/content/logs/lm/01Kp7"

No kpt file found, generating kpts...
No kpt file found, generating kpts...
Evaluation on 01

📂 Evaluating 000509.png
🔺 ADD  (mm): 87.02 | Threshold: 14.21 mm
🔺 ADD after ICP  (mm): 47.76 | Threshold: 14.21 mm
───────────────

📂 Evaluating 001136.png
🔺 ADD  (mm): 62.71 | Threshold: 14.21 mm
🔺 ADD after ICP  (mm): 12.81 | Threshold: 14.21 mm
───────────────

📂 Evaluating 000229.png
🔺 ADD  (mm): 69.75 | Threshold: 14.21 mm
🔺 ADD after ICP  (mm): 58.24 | Threshold: 14.21 mm
───────────────

📂 Evaluating 000676.png
🔺 ADD  (mm): 73.58 | Threshold: 14.21 mm
🔺 ADD after ICP  (mm): 62.27 | Threshold: 14.21 mm
───────────────

📂 Evaluating 000994.png
🔺 ADD  (mm): 70.80 | Threshold: 14.21 mm
🔺 ADD after ICP  (mm): 56.18 | Threshold: 14.21 mm
───────────────

📂 Evaluating 000869.png
object address  : 0x7b93c0881c60
object refcount : 2
object type     : 0x9d5ea0
object type name: KeyboardInterrupt
object repr     : KeyboardInterrupt()
lost sys.stderr
^C


# **تمامی داده ها در مقیاس میلی متر هستند**