# **Configure Google Colab Settings**

In [6]:
#Connect to personal Google Drive space
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#Change directory
%cd /content/
#Create Paths
!mkdir /content/dataset/
!mkdir /content/dataset/linemod/
!mkdir /content/dataset/linemod/Linemod_preprocessed/

/content


In [ ]:
import zipfile
import os
from tqdm import tqdm

zip_path = "/content/drive/MyDrive/Linemod_preprocessed.zip"
extract_to = "/content/dataset/linemod/"

# ایجاد مسیر خروجی اگر وجود ندارد
os.makedirs(extract_to, exist_ok=True)

# باز کردن فایل zip
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # گرفتن لیست فایل‌ها
    file_list = zip_ref.infolist()

    print(f"📦 Extracting {len(file_list)} files...\n")
    for file in tqdm(file_list, desc="Unzipping", unit="file"):
        zip_ref.extract(file, extract_to)

print("\n✅ Extraction complete.")


📦 Extracting 62142 files...



Unzipping: 100%|██████████| 62142/62142 [01:45<00:00, 591.28file/s]  


✅ Extraction complete.


# **Configure Github Settings**

In [ ]:
#Generate SSH Key
!ssh-keygen -t ed25519 -C "" -f ~/.ssh/id_ed25519 -N ""

Generating public/private ed25519 key pair.
Created directory '/root/.ssh'.
Your identification has been saved in /root/.ssh/id_ed25519
Your public key has been saved in /root/.ssh/id_ed25519.pub
The key fingerprint is:
SHA256:YSO9xBQFqn4ogONNzq9K/uj5HLnswwh/XASV3qMIgLo 
The key's randomart image is:
+--[ED25519 256]--+
|.    ...++.      |
|o   . .=         |
|..   oo.B        |
|o .  .o+o+       |
|+. o.o .S.       |
|Eo=.o.o          |
|.++Bo..          |
|o.*+*.           |
|.*=Xo.           |
+----[SHA256]-----+


In [ ]:
#Print SSH Key
!cat ~/.ssh/id_ed25519.pub

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDey85dBLh+MKR6vvr7B0uAFMZZVl+IJRutIIwHOt565 


In [ ]:
#Store Public SSH Key
!mkdir -p ~/.ssh
!ssh-keyscan github.com >> ~/.ssh/known_hosts

# github.com:22 SSH-2.0-4c545346
# github.com:22 SSH-2.0-4c545346
# github.com:22 SSH-2.0-4c545346
# github.com:22 SSH-2.0-4c545346
# github.com:22 SSH-2.0-4c545346


In [1]:
#Install/Upgrade Git
!apt-get install git
!apt upgrade git

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.12).
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.12).
Calculating upgrade... Done
The following packages have been kept back:
  libcudnn9-cuda-12 libcudnn9-dev-cuda-12 libldap-2.5-0 libnccl-dev libnccl2
The following packages will be upgraded:
  base-files binutils binutils-common binutils-x86-64-linux-gnu
  cuda-toolkit-12-config-common cuda-toolkit-config-common e2fsprogs
  libbinutils libc-bin libcap2 libctf-nobfd0 libctf0 libext2fs2 libgnutls30
  libpam-modules libpam-modules-bin libpam-runtime libpam0g libperl5.34
  libseccomp2 libss2 libtasn1-6 libudev1 linux-libc-dev logsave openssl perl
  perl-base perl-modules-5.34
29 upgraded, 0 newly installed, 0 to remove and 

### **Clone project from Github**



In [ ]:
#Create Directory for Project to clone
!mkdir /content/project
#Clone Project from Github - Specify the path
!git clone https://github.com/mldl-team/6D-pose-estimation.git /content/project/6D-pose-estimation

Cloning into '/content/project/6D-pose-estimation'...
remote: Enumerating objects: 117, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 117 (delta 7), reused 22 (delta 4), pack-reused 92 (from 1)
Receiving objects: 100% (117/117), 115.54 MiB | 23.35 MiB/s, done.
Resolving deltas: 100% (18/18), done.


### **Copy modified project into the cloned path**

In [ ]:
#Copy the file into cloned project
!cp "/content/drive/MyDrive/Colab Notebooks/MLDL.ipynb" "/content/6D-pose-estimation/"

cp: cannot stat '/content/drive/MyDrive/Colab Notebooks/MLDL.ipynb': No such file or directory


### **Push the modified project into Github**

In [ ]:
%cd /content/6D-pose-estimation

#Config Git
!git config --global user.email "sina.ghiabi1@gmail.com"
!git config --global user.name "sina-ghiabi"

#Push the Project into Github
!git add .
!git commit -m "Start"
!git push origin main
%cd /content/

[Errno 2] No such file or directory: '/content/6D-pose-estimation'
/content/dataset/linemod
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
/content


# **Configure Wandb Settings**

In [ ]:
#Wandb installation
!pip install wandb

In [ ]:
!wandb login

wandb: WARNING Using legacy-service, which is deprecated. If this is unintentional, you can fix it by ensuring you do not call `wandb.require('legacy-service')` and do not set the WANDB_X_REQUIRE_LEGACY_SERVICE environment variable.
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit: 
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: sina-ghiabi (erythm-mldl) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin


In [ ]:
import random

import wandb

# Start a new wandb run to track this script.
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="erythm-mldl",
    # Set the wandb project where this run will be logged.
    project="6D",
    # Track hyperparameters and run metadata.
    config={
        "learning_rate": 0.02,
        "architecture": "CNN",
        "dataset": "CIFAR-100",
        "epochs": 10,
    },
)

# Simulate training.
epochs = 10
offset = random.random() / 5
for epoch in range(2, epochs):
    acc = 1 - 2**-epoch - random.random() / epoch - offset
    loss = 2**-epoch + random.random() / epoch + offset

    # Log metrics to wandb.
    run.log({"acc": acc, "loss": loss})

# Finish the run and upload any remaining data.
run.finish()

wandb: Currently logged in as: sina-ghiabi (erythm-mldl) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin


# **Configure Python**

In [ ]:
#Install Python
!pip install ipython

#Usage of the library is to display input or output images
from IPython.display import Image, display

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 44.2 MB/s eta 0:00:00


# **Configure PyTorch**

In [ ]:
#Install PyTorch
!pip install torch
!pip install torch torchvision opencv-python matplotlib tqdm pyyaml
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

#Usage of the library is the primary neural network computation framework.
import torch
torch.__version__

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 128.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 99.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 54.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 12.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 45.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 19.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 108.3 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvji

'2.6.0+cu124'

# **Configure YOLO**

In [ ]:
#Usage of the library is To run Object Detection & Image Classification with YOLO
!pip install ultralytics

#Check availability of ultralytics
!ultralytics.checks()

import ultralytics

from ultralytics import YOLO

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 24.5 MB/s eta 0:00:00
/bin/bash: -c: line 2: syntax error: unexpected end of file
Creating new Ultralytics Settings v0.0.6 file ✅ 
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.


# **Configure OpenCV**

In [ ]:
#Usage of the library is for real‐time image and video processing
!pip install opencv-python

import cv2

In [ ]:
#Check if we have an access to nvidia
#If "/bin/bash: line 1: nvidia-smi: command not found" appeared, change Runtime to GPU
!nvidia-smi

Tue May 20 06:51:18 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   32C    P0             46W /  400W |       0MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

# **Configure Open3D**
### **Open3D is used for 3D geometry processing in Pose Estimation, SciPy for scientific computations**

In [ ]:
!pip install open3d scipy numpy
!pip install opencv-python tensorboard pyyaml scipy scikit-image
!pip install tensorboardX

import open3d as o3d
from scipy.spatial import distance_matrix
import numpy as np

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 5.0 MB/s eta 0:00:00


### **Manage file paths with os Library**

In [ ]:
import os
import glob

#Examples
#img_path = os.path.join('data', 'images', img_name)
#images = glob.glob('data/images/*.jpg')
#labels = glob.glob('data/labels/*.txt')

### **Progress Bar**

In [ ]:
!pip install tqdm
from tqdm import tqdm

# **Object Detection**


### **Import all the Tools**

In [ ]:
import torch
import matplotlib.pyplot as plt
import cv2
import numpy as np
from ultralytics import YOLO

#Choose YOLO Model
model = YOLO('yolov8s.pt')
#Choose Computing Device - CUDA: Compute Unified Device Architecture
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
#Transfer Model to Computing Device
model.to(device)

100%|██████████| 21.5M/21.5M [00:00<00:00, 140MB/s] 


YOLO(
  (model): DetectionModel(
    (model): Sequential(
      (0): Conv(
        (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): C2f(
        (cv1): Conv(
          (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(96, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_s

### **Make Dataset Ready**

In [ ]:
import os
import yaml
import random
import shutil
from PIL import Image
from collections import defaultdict, Counter
from tqdm import tqdm

# ================== CONFIGURATION ======================
!mkdir /content/dataset/linemod/Linemod_ready
root_dir = '/content/dataset/linemod/Linemod_preprocessed/data'
output_base = '/content/dataset/linemod/Linemod_ready'  # Base output folder
img_out_train = os.path.join(output_base, 'images/train')
img_out_val = os.path.join(output_base, 'images/val')
label_out_train = os.path.join(output_base, 'labels/train')
label_out_val = os.path.join(output_base, 'labels/val')

# Create directories if they don't exist
for path in [img_out_train, img_out_val, label_out_train, label_out_val]:
    os.makedirs(path, exist_ok=True)

# Define valid class IDs and their YOLO-mapped indices (0-based)
existing_classes = [1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15]
#Create {cls_id: idx}: {0:1} - {1:2} - {2:4} - {3:5} ...
class_map = {cls_id: idx for idx, cls_id in enumerate(existing_classes)}

# ================ STEP 1: GATHER SAMPLES ===================
samples_by_class = defaultdict(list)
for cls in existing_classes:
    folder_path = os.path.join(root_dir, f"{cls:02d}")
    rgb_folder = os.path.join(folder_path, 'rgb')
    gt_file = os.path.join(folder_path, 'gt.yml')

    if not os.path.exists(gt_file):
        print(f"⚠️ Class {cls:02d} missing → skipped.")
        continue

    with open(gt_file, 'r') as f:
        gt_data = yaml.safe_load(f)

    for img_id in gt_data:
        img_path = os.path.join(rgb_folder, f"{int(img_id):04d}.png")
        if os.path.exists(img_path):
            samples_by_class[cls].append(img_id)

# Display class distribution
print("🔍 Class distribution:")
for cls, samples in samples_by_class.items():
    print(f"Class {cls:>2}: {len(samples)} samples")

# =============== STEP 2: LABEL AND IMAGE PROCESSING =================
def save_yolo_labels(sample_list, mode, cls, gt_data, rgb_folder):
    label_dir = label_out_train if mode == 'train' else label_out_val
    img_dir = img_out_train if mode == 'train' else img_out_val
    label_id = class_map[cls]

    for img_id in sample_list:
        img_path = os.path.join(rgb_folder, f"{int(img_id):04d}.png")
        img = Image.open(img_path)
        w, h = img.size

        bbox = gt_data[img_id][0]['obj_bb']
        x, y, bw, bh = bbox
        x_center = (x + bw / 2) / w
        y_center = (y + bh / 2) / h
        norm_bw = bw / w
        norm_bh = bh / h

        # Save label
        label_file = f"{cls:02d}_{int(img_id):04d}.txt"
        with open(os.path.join(label_dir, label_file), 'w') as f:
            f.write(f"{label_id} {x_center:.6f} {y_center:.6f} {norm_bw:.6f} {norm_bh:.6f}\n")

        # Save image
        img_out_path = os.path.join(img_dir, f"{cls:02d}_{int(img_id):04d}.png")
        shutil.copy(img_path, img_out_path)

# Split, save labels and copy images
print("\n⚙️ Processing and splitting images...")
for cls, samples in samples_by_class.items():
    random.shuffle(samples)
    split_idx = int(0.8 * len(samples))
    train_samples = samples[:split_idx]
    val_samples = samples[split_idx:]

    folder_path = os.path.join(root_dir, f"{cls:02d}")
    rgb_folder = os.path.join(folder_path, 'rgb')
    gt_file = os.path.join(folder_path, 'gt.yml')

    with open(gt_file, 'r') as f:
        gt_data = yaml.safe_load(f)

    save_yolo_labels(train_samples, 'train', cls, gt_data, rgb_folder)
    save_yolo_labels(val_samples, 'val', cls, gt_data, rgb_folder)

# ============= STEP 3: LABEL DISTRIBUTION STATS ===============
def count_labels(label_dir):
    counter = Counter()
    for filename in os.listdir(label_dir):
        if filename.endswith('.txt'):
            with open(os.path.join(label_dir, filename), 'r') as f:
                for line in f:
                    class_id = int(line.strip().split()[0])
                    counter[class_id] += 1
    return counter

train_counts = count_labels(label_out_train)
val_counts = count_labels(label_out_val)

import pandas as pd
df_stats = pd.DataFrame({
    "Train Count": pd.Series(train_counts),
    "Validation Count": pd.Series(val_counts)
}).fillna(0).astype(int)

print(df_stats)

print("✅ YOLO dataset generated, split, and labeled.")

🔍 Class distribution:
Class  1: 1236 samples
Class  2: 1214 samples
Class  4: 1201 samples
Class  5: 1196 samples
Class  6: 1179 samples
Class  8: 1188 samples
Class  9: 1254 samples
Class 10: 1253 samples
Class 11: 1220 samples
Class 12: 1237 samples
Class 13: 1152 samples
Class 14: 1227 samples
Class 15: 1243 samples

⚙️ Processing and splitting images...
    Train Count  Validation Count
0           988               248
1           971               243
2           960               241
3           956               240
4           943               236
5           950               238
6          1003               251
7          1002               251
8           976               244
9           989               248
10          921               231
11          981               246
12          994               249
✅ YOLO dataset generated, split, and labeled.


### **Train the Model**

In [ ]:
model.train(
    data='/content/project/6D-pose-estimation/configs/linemod_final.yaml',
    epochs=15,
    imgsz=640,
    batch=8,
    device=0,
    patience=5,
    weight_decay=0.0005
)

In [ ]:
!cp -r runs/detect/train ~/6d/yolo_logs/

### **Save Trained Model Metrics**

In [ ]:
from ultralytics import YOLO

model = YOLO("model.pt")
metrics = model.val(data="linemod_final.yaml", plots=True, save=True)

# **Pose Estimation**

### Clone RCVPose from Github

In [ ]:
!rm -rf /content/rcvpose

In [ ]:
#Create Directory for RCVPose Estimation Tool
%cd /content
!git clone https://github.com/aaronWool/rcvpose.git

/content
Cloning into 'rcvpose'...
remote: Enumerating objects: 1556, done.
remote: Counting objects: 100% (121/121), done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 1556 (delta 47), reused 98 (delta 36), pack-reused 1435 (from 1)
Receiving objects: 100% (1556/1556), 17.51 MiB | 38.72 MiB/s, done.
Resolving deltas: 100% (679/679), done.


### **Prepare File & Folders for RCVPose**

### 1 - Move Objects' Models From models Folder To Class Folders & Rename Them To mesh.ply

In [ ]:
import os
import shutil

# ==== CONFIGURATION ====
# Base directory for preprocessed model data
data_path = "/content/dataset/linemod/Linemod_preprocessed/data"
# Directory containing original model files
models_path = "/content/dataset/linemod/Linemod_preprocessed/models"

for filename in os.listdir(models_path):
    # Only process files matching the pattern obj_<id>.ply
    if not filename.startswith("obj_") or not filename.endswith(".ply"):
        continue

    # Extract the model identifier (e.g., "01")
    model_id = filename.split("_")[1].split(".")[0]  # example: "01"
    src_file = os.path.join(models_path, filename)
    dst_folder = os.path.join(data_path, model_id)

    # Skip if the destination folder does not exist
    if not os.path.isdir(dst_folder):
        print(f"Folder {model_id} does not exist → skipped")
        continue

    # Copy and rename the model file to mesh.ply
    dst_file = os.path.join(dst_folder, "mesh.ply")
    print(f"Copying {filename} → {dst_file}")
    shutil.copy2(src_file, dst_file)

print("\n✅ Model files have been moved and renamed to mesh.ply.")


Copying obj_13.ply → /content/dataset/linemod/Linemod_preprocessed/data/13/mesh.ply
Folder 03 does not exist → skipped
Copying obj_10.ply → /content/dataset/linemod/Linemod_preprocessed/data/10/mesh.ply
Copying obj_15.ply → /content/dataset/linemod/Linemod_preprocessed/data/15/mesh.ply
Copying obj_12.ply → /content/dataset/linemod/Linemod_preprocessed/data/12/mesh.ply
Copying obj_05.ply → /content/dataset/linemod/Linemod_preprocessed/data/05/mesh.ply
Copying obj_11.ply → /content/dataset/linemod/Linemod_preprocessed/data/11/mesh.ply
Folder 07 does not exist → skipped
Copying obj_14.ply → /content/dataset/linemod/Linemod_preprocessed/data/14/mesh.ply
Copying obj_01.ply → /content/dataset/linemod/Linemod_preprocessed/data/01/mesh.ply
Copying obj_08.ply → /content/dataset/linemod/Linemod_preprocessed/data/08/mesh.ply
Copying obj_04.ply → /content/dataset/linemod/Linemod_preprocessed/data/04/mesh.ply
Copying obj_02.ply → /content/dataset/linemod/Linemod_preprocessed/data/02/mesh.ply
Copyin

### 2 - Create Outside9.npy From Objects' Models
A NumPy file containing a [9, 3] array of 3D keypoint coordinates sampled from the object mesh using Farthest-Point Sampling. These five points are chosen to maximally span the surface of the model. During data preprocessing, each keypoint is used to generate a per-frame radial distance map: for every pixel with valid depth, its Euclidean distance in 3D space to each keypoint is computed and stored. These distance maps serve as ground-truth supervision when training a network to predict 3D distance fields from RGB-D inputs.


In [ ]:
import os
import numpy as np
import open3d as o3d

def fps(points: np.ndarray, k: int, seed: int = 0) -> np.ndarray:
    """
    Farthest-Point Sampling:
      - points: (N,3) array of XYZ samples
      - k: number of keypoints to pick
    Returns an array of shape (k,3).
    """
    np.random.seed(seed)
    N = points.shape[0]
    centroids = np.zeros((k,), dtype=np.int32)
    distances = np.full((N,), np.inf)
    farthest = np.random.randint(0, N)
    for i in range(k):
        centroids[i] = farthest
        centroid = points[farthest]
        dist = np.sum((points - centroid)**2, axis=1)
        distances = np.minimum(distances, dist)
        farthest = np.argmax(distances)
    return points[centroids]

# --- Define base path and class list ---
base_dir = "/content/dataset/linemod/Linemod_preprocessed/data"
classes = ['01','02','04','05','06','08','09','10','11','12','13','14','15']

for cls in classes:
    seq_dir = os.path.join(base_dir, cls)
    mesh_path = os.path.join(seq_dir, "mesh.ply")

    if not os.path.isfile(mesh_path):
        print(f"⚠️  Skipping {cls}: mesh.ply not found at {mesh_path}")
        continue

    print(f"🎯 Processing class {cls}")

    # Load point cloud
    pcd = o3d.io.read_point_cloud(mesh_path)
    pts = np.asarray(pcd.points)

    if pts.shape[0] < 9:
        print(f"❌ Not enough points in {mesh_path} (only {pts.shape[0]}), skipping.")
        continue

    # Perform Farthest-Point Sampling
    keypoints = fps(pts, k=9, seed=42)

    # Save output
    out_path = os.path.join(seq_dir, "Outside9.npy")
    np.save(out_path, keypoints)
    print(f"✅ Saved {out_path} (shape {keypoints.shape})")

    # Test load to confirm file is valid
    try:
        test = np.load(out_path)
        print(f"📦 Verified file: {out_path} loaded successfully with shape {test.shape}\n")
    except Exception as e:
        print(f"❌ Failed to load saved file: {e}\n")


🎯 Processing class 01
✅ Saved /content/dataset/linemod/Linemod_preprocessed/data/01/Outside9.npy (shape (9, 3))
📦 Verified file: /content/dataset/linemod/Linemod_preprocessed/data/01/Outside9.npy loaded successfully with shape (9, 3)

🎯 Processing class 02
✅ Saved /content/dataset/linemod/Linemod_preprocessed/data/02/Outside9.npy (shape (9, 3))
📦 Verified file: /content/dataset/linemod/Linemod_preprocessed/data/02/Outside9.npy loaded successfully with shape (9, 3)

🎯 Processing class 04
✅ Saved /content/dataset/linemod/Linemod_preprocessed/data/04/Outside9.npy (shape (9, 3))
📦 Verified file: /content/dataset/linemod/Linemod_preprocessed/data/04/Outside9.npy loaded successfully with shape (9, 3)

🎯 Processing class 05
✅ Saved /content/dataset/linemod/Linemod_preprocessed/data/05/Outside9.npy (shape (9, 3))
📦 Verified file: /content/dataset/linemod/Linemod_preprocessed/data/05/Outside9.npy loaded successfully with shape (9, 3)

🎯 Processing class 06
✅ Saved /content/dataset/linemod/Linem

### It is only Possible to see the content of Outside9.npy using code below

In [ ]:
import numpy as np
import os

base_path = "/content/dataset/linemod/Linemod_preprocessed/data"

# لیست کلاس‌ها از 01 تا 15 (بدون 03 و 07 چون معمولاً در Linemod نیستند)
classes = ['01','02','04','05','06','08','09','10','11','12','13','14','15']

for cls in classes:
    file_path = os.path.join(base_path, cls, "Outside9.npy")

    if not os.path.isfile(file_path):
        print(f"⚠️ File not found for class {cls}: {file_path}")
        continue

    print(f"📂 Class {cls}'s Outside9.npy:")
    data = np.load(file_path)
    print(data, "\n")


📂 Class 01's Outside9.npy:
[[-20.3664  19.3442  -7.6361]
 [ 35.6255 -16.9712 -44.263 ]
 [  7.5111  -4.4303  41.4566]
 [ -1.604  -33.9459  -5.4867]
 [-26.6571 -13.9838 -43.0416]
 [ 10.2731  20.1762 -40.7712]
 [ 13.9023  17.8718   9.8713]
 [-20.7606  -9.8099  16.1704]
 [ 30.0282 -21.3168 -10.4571]] 

📂 Class 02's Outside9.npy:
[[  12.3025  -17.8971   43.9721]
 [  90.5719   -1.9537 -107.092 ]
 [ -70.8535   22.383   -92.6023]
 [  53.2234   58.4881  -23.509 ]
 [   7.5829  -29.9273  -56.5234]
 [ -92.0255   -4.1247   -3.2999]
 [  66.5464    0.135   107.388 ]
 [  86.4643  -24.3331  -25.008 ]
 [ -11.3591   30.5359   -5.3499]] 

📂 Class 04's Outside9.npy:
[[-60.7914  62.0638 -19.3466]
 [ 67.0034 -10.3907  -2.8697]
 [-54.8219 -67.9932  19.5177]
 [-10.7869  13.9897  49.5203]
 [-19.0693 -15.506  -47.6997]
 [ 17.4433  49.3472 -20.1936]
 [-66.316   -0.8159   7.7016]
 [  4.4803 -41.5652  16.038 ]
 [-56.6145 -67.7992 -45.8652]] 

📂 Class 05's Outside9.npy:
[[ -8.0273  55.7049 -79.5385]
 [  1.2705   6.3

### **3 - Generate Pose For Each Picture Using ICP (Iterative Closest Point) With RGB, Depth, Mask & Mesh.ply**

Purpose: This script generates pose files (Rotation & Translation matrices) for each image in the dataset.

How it works:
1. Reads the depth image and removes the background using the mask.
2. Converts the depth into a point cloud (scene point cloud).
3. Loads the 3D model (`mesh.ply`) and samples it into a point cloud.
4. Uses ICP to align the model point cloud with the scene point cloud.
5. Saves the resulting [R|t] matrix as a `.npy` file named `poseXXXXXX.npy`.

Output:
Each frame will have a file like `pose000123.npy` in the `pose/` folder.
It contains a 3×4 RT matrix with:
- R: rotation (3×3)
- t: translation (3×1)

Use in RCVPose:
These pose files are used to:
- Project 3D keypoints onto 2D image space
- Generate 3D radius maps
- Serve as ground truth during training

Requirements:
- `.dpt` depth images
- `.png` binary masks
- 3D model in `.ply` format
- Camera intrinsics `K`


In [ ]:
import os
import numpy as np
import open3d as o3d
from PIL import Image
from tqdm import tqdm  # ✅ for progress bar

# List of class folders
class_ids = ['01', '02', '04', '05', '06', '08', '09', '10', '11', '12', '13', '14', '15']

# Base dataset path
base_root = "/content/dataset/linemod/Linemod_preprocessed/data/"

# Camera intrinsics for LINEMOD
K = np.array([[572.4114, 0., 325.2611],
              [0., 573.57043, 242.04899],
              [0., 0., 1.]])
depth_scale = 1000.0  # convert mm to meters

# Loop through all classes
for class_id in class_ids:
    print(f"\n📂 Processing class {class_id}...")
    base_path = os.path.join(base_root, class_id)
    rgb_dir = os.path.join(base_path, "rgb")
    depth_dir = os.path.join(base_path, "depth")
    mask_dir = os.path.join(base_path, "mask")
    ply_path = os.path.join(base_path, "mesh.ply")
    pose_dir = os.path.join(base_path, "pose")

    if not os.path.exists(pose_dir):
        os.makedirs(pose_dir)

    mesh = o3d.io.read_triangle_mesh(ply_path)
    model_pcd = mesh.sample_points_uniformly(number_of_points=10000)
    model_pcd.estimate_normals()

    depth_files = sorted([f for f in os.listdir(depth_dir) if f.endswith(".png")])
    for filename in tqdm(depth_files, desc=f"Class {class_id}", unit="file"):
        idx = os.path.splitext(filename)[0]

        # Read depth image (16-bit PNG)
        depth_path = os.path.join(depth_dir, filename)
        depth_img = Image.open(depth_path)
        depth = np.array(depth_img).astype(np.float32) / depth_scale
        h, w = depth.shape

        # Read mask and remove background
        mask_path = os.path.join(mask_dir, f"{idx.zfill(4)}.png")
        if not os.path.exists(mask_path):
            tqdm.write(f"⚠️ Mask missing for {class_id}/{idx.zfill(4)}.png — skipped. \n")
            continue
        mask = np.array(Image.open(mask_path))
        if len(mask.shape) == 3:
            mask = mask[:, :, 0]
        depth[mask == 0] = 0

        # Create point cloud
        intrinsic = o3d.camera.PinholeCameraIntrinsic(w, h, K[0, 0], K[1, 1], K[0, 2], K[1, 2])
        depth_o3d = o3d.geometry.Image((depth * depth_scale).astype(np.uint16))
        rgbd = o3d.geometry.RGBDImage.create_from_color_and_depth(
            o3d.geometry.Image((depth * 255).astype(np.uint8)),
            depth_o3d,
            depth_scale=depth_scale,
            convert_rgb_to_intensity=False
        )
        pcd = o3d.geometry.PointCloud.create_from_depth_image(rgbd.depth, intrinsic)
        pcd.estimate_normals()

        reg = o3d.pipelines.registration.registration_icp(
            model_pcd, pcd, max_correspondence_distance=0.02,
            estimation_method=o3d.pipelines.registration.TransformationEstimationPointToPlane(),
            criteria=o3d.pipelines.registration.ICPConvergenceCriteria(max_iteration=200)
        )

        RT = reg.transformation[:3, :]

        # ✅ Save as poseXXXXXX.npy with 6-digit zero-padded format
        save_path = os.path.join(pose_dir, f"pose{int(idx):06d}.npy")
        np.save(save_path, RT)

print("\n🎉 Done generating poses for all classes.")



📂 Processing class 01...


Class 01: 100%|██████████| 1236/1236 [00:26<00:00, 46.06file/s]



📂 Processing class 02...


Class 02: 100%|██████████| 1214/1214 [00:37<00:00, 31.96file/s]



📂 Processing class 04...


Class 04: 100%|██████████| 1201/1201 [00:32<00:00, 36.99file/s]



📂 Processing class 05...


Class 05: 100%|██████████| 1196/1196 [00:36<00:00, 33.09file/s]



📂 Processing class 06...


Class 06: 100%|██████████| 1179/1179 [00:27<00:00, 43.17file/s]



📂 Processing class 08...


Class 08: 100%|██████████| 1188/1188 [00:40<00:00, 29.60file/s]



📂 Processing class 09...


Class 09: 100%|██████████| 1254/1254 [00:29<00:00, 42.92file/s]



📂 Processing class 10...


Class 10: 100%|██████████| 1253/1253 [00:36<00:00, 34.33file/s]



📂 Processing class 11...


Class 11: 100%|██████████| 1220/1220 [00:28<00:00, 43.52file/s]



📂 Processing class 12...


Class 12: 100%|██████████| 1237/1237 [00:37<00:00, 32.61file/s]



📂 Processing class 13...


Class 13: 100%|██████████| 1152/1152 [00:39<00:00, 29.40file/s]



📂 Processing class 14...


Class 14: 100%|██████████| 1227/1227 [00:49<00:00, 24.90file/s]



📂 Processing class 15...


Class 15: 100%|██████████| 1243/1243 [00:33<00:00, 36.87file/s]

⚠️ Mask missing for 15/1225.png — skipped. 

⚠️ Mask missing for 15/1226.png — skipped. 

⚠️ Mask missing for 15/1227.png — skipped. 

⚠️ Mask missing for 15/1228.png — skipped. 

⚠️ Mask missing for 15/1229.png — skipped. 

⚠️ Mask missing for 15/1230.png — skipped. 

⚠️ Mask missing for 15/1231.png — skipped. 

⚠️ Mask missing for 15/1232.png — skipped. 

⚠️ Mask missing for 15/1233.png — skipped. 

⚠️ Mask missing for 15/1234.png — skipped. 

⚠️ Mask missing for 15/1235.png — skipped. 

⚠️ Mask missing for 15/1236.png — skipped. 

⚠️ Mask missing for 15/1237.png — skipped. 

⚠️ Mask missing for 15/1238.png — skipped. 

⚠️ Mask missing for 15/1239.png — skipped. 

⚠️ Mask missing for 15/1240.png — skipped. 

⚠️ Mask missing for 15/1241.png — skipped. 

⚠️ Mask missing for 15/1242.png — skipped. 


🎉 Done generating poses for all classes.


### 4 - Modify RGB, Mask, Depth Files Format From 4 Digits to 6 Digits - Radius Map Needs Files in 6-Digit Format

In [ ]:
from tqdm import tqdm
import os

def rename_files_to_6_digit(base_dir, classes):
    for cls in classes:
        print(f"\n🔧 Renaming files in class {cls} ...")

        for folder_name in ['rgb','mask', 'depth']:
            folder_path = os.path.join(base_dir, cls, folder_name)
            if not os.path.isdir(folder_path):
                print(f"⚠️ Skipping {cls}/{folder_name}: folder not found.")
                continue

            file_list = [f for f in os.listdir(folder_path) if os.path.splitext(f)[0].isdigit()]
            for fname in tqdm(file_list, desc=f"{cls}/{folder_name}", unit="file"):
                name, ext = os.path.splitext(fname)
                idx = int(name)
                new_name = f"{idx:06d}{ext}"
                src = os.path.join(folder_path, fname)
                dst = os.path.join(folder_path, new_name)
                os.rename(src, dst)

    print("\n✅ All depth and mask files renamed to 6-digit format.")

# === Set base path and class list ===
base_dir = "/content/dataset/linemod/Linemod_preprocessed/data"
classes = ['01','02','04','05','06','08','09','10','11','12','13','14','15']

rename_files_to_6_digit(base_dir, classes)



🔧 Renaming files in class 01 ...


01/depth: 100%|██████████| 1236/1236 [00:00<00:00, 44813.88file/s]



🔧 Renaming files in class 02 ...


02/depth: 100%|██████████| 1214/1214 [00:00<00:00, 46161.45file/s]



🔧 Renaming files in class 04 ...


04/depth: 100%|██████████| 1201/1201 [00:00<00:00, 47684.20file/s]



🔧 Renaming files in class 05 ...


05/depth: 100%|██████████| 1196/1196 [00:00<00:00, 47150.04file/s]



🔧 Renaming files in class 06 ...


06/depth: 100%|██████████| 1179/1179 [00:00<00:00, 48546.90file/s]



🔧 Renaming files in class 08 ...


08/depth: 100%|██████████| 1188/1188 [00:00<00:00, 46910.06file/s]



🔧 Renaming files in class 09 ...


09/depth: 100%|██████████| 1254/1254 [00:00<00:00, 44714.33file/s]



🔧 Renaming files in class 10 ...


10/depth: 100%|██████████| 1253/1253 [00:00<00:00, 46491.24file/s]



🔧 Renaming files in class 11 ...


11/depth: 100%|██████████| 1220/1220 [00:00<00:00, 47049.02file/s]



🔧 Renaming files in class 12 ...


12/depth: 100%|██████████| 1237/1237 [00:00<00:00, 47391.32file/s]



🔧 Renaming files in class 13 ...


13/depth: 100%|██████████| 1152/1152 [00:00<00:00, 46846.01file/s]



🔧 Renaming files in class 14 ...


14/depth: 100%|██████████| 1227/1227 [00:00<00:00, 47383.45file/s]



🔧 Renaming files in class 15 ...


15/depth: 100%|██████████| 1243/1243 [00:00<00:00, 46853.83file/s]


✅ All depth and mask files renamed to 6-digit format.


###5 -  Convert Depth files from .png to .dpt - Radius Map Needs Depth Files With .dpt Format

In [ ]:
import os
import numpy as np
from PIL import Image
import struct

def save_dpt_file(png_path, dpt_path, scale=1.0):
    """
    Converts a depth .png file to a .dpt file with proper binary format:
    [uint32 height][uint32 width][uint16 depth values]
    Then deletes the original .png file.
    """
    depth_img = np.array(Image.open(png_path)).astype(np.float32)
    depth_img = (depth_img * scale).astype(np.uint16)

    h, w = depth_img.shape

    with open(dpt_path, 'wb') as f:
        f.write(struct.pack('I', h))
        f.write(struct.pack('I', w))
        f.write(depth_img.tobytes())

    # Delete the original .png file after successful conversion
    os.remove(png_path)

def convert_all_png_to_dpt_in_classes(base_dir, classes, scale=1.0):
    """
    Processes all PNG files in the 'depth' folder of each class and creates corresponding .dpt files.
    """
    for cls in classes:
        depth_dir = os.path.join(base_dir, cls, "depth")
        if not os.path.exists(depth_dir):
            print(f"⚠️ Skipping class {cls}: no depth folder found.")
            continue

        print(f"\n🔍 Processing class {cls}...")

        png_files = sorted([f for f in os.listdir(depth_dir) if f.endswith(".png")])
        for fname in tqdm(png_files, desc=f"Class {cls}", unit="file"):
            png_path = os.path.join(depth_dir, fname)
            dpt_path = os.path.join(depth_dir, os.path.splitext(fname)[0] + ".dpt")
            save_dpt_file(png_path, dpt_path, scale)

    print("\n✅ All PNG files have been converted to .dpt format.")

# === Base dataset path and class list ===
base_dir = "/content/dataset/linemod/Linemod_preprocessed/data"
classes = ['01','02','04','05','06','08','09','10','11','12','13','14','15']

# PNG values are already in mm → no scaling needed
scale = 1.0

convert_all_png_to_dpt_in_classes(base_dir, classes, scale)



🔍 Processing class 01...


Class 01: 100%|██████████| 1236/1236 [00:04<00:00, 291.97file/s]



🔍 Processing class 02...


Class 02: 100%|██████████| 1214/1214 [00:04<00:00, 286.72file/s]



🔍 Processing class 04...


Class 04: 100%|██████████| 1201/1201 [00:04<00:00, 283.32file/s]



🔍 Processing class 05...


Class 05: 100%|██████████| 1196/1196 [00:04<00:00, 286.86file/s]



🔍 Processing class 06...


Class 06: 100%|██████████| 1179/1179 [00:04<00:00, 284.81file/s]



🔍 Processing class 08...


Class 08: 100%|██████████| 1188/1188 [00:04<00:00, 286.06file/s]



🔍 Processing class 09...


Class 09: 100%|██████████| 1254/1254 [00:04<00:00, 290.75file/s]



🔍 Processing class 10...


Class 10: 100%|██████████| 1253/1253 [00:04<00:00, 284.82file/s]



🔍 Processing class 11...


Class 11: 100%|██████████| 1220/1220 [00:04<00:00, 288.47file/s]



🔍 Processing class 12...


Class 12: 100%|██████████| 1237/1237 [00:04<00:00, 282.15file/s]



🔍 Processing class 13...


Class 13: 100%|██████████| 1152/1152 [00:04<00:00, 284.31file/s]



🔍 Processing class 14...


Class 14: 100%|██████████| 1227/1227 [00:04<00:00, 283.35file/s]



🔍 Processing class 15...


Class 15: 100%|██████████| 1243/1243 [00:04<00:00, 282.93file/s]


✅ All PNG files have been converted to .dpt format.


### 3 - Generate Radius Map

We compute the mesh and keypoints to:

* Mesh, accurately represent an object’s 3D shape.
* Reduce complexity by sampling a few representative points.
* Enable fast registration and matching across views.
* Support precise pose estimation via 3D–2D point correspondences.
* Improve efficiency in real-time or learning-based applications.


### کاری که این فایل انجام می دهد:

### مدل سه‌بعدی را از فایل .ply و نقاط کلیدی را از Outside9.npy بارگذاری می‌کند.

### تصاویر عمق (depth) و ماسک‌ها (mask) را از مسیر مشخص‌شده می‌خواند.

### با استفاده از ماتریس کالیبراسیون دوربین و ماتریس تبدیل (RT)، نقاط مدل را به فضای دوبعدی تصویر انتقال می‌دهد.

### مختصات سه‌بعدی نقاط را از تصاویر عمق به دست می‌آورد.

### فاصله هر نقطه را نسبت به نقاط کلیدی مشخص می‌کند.

### بر اساس این فواصل، یک نقشه شعاعی (Radius3DMap) تولید کرده و آن‌ها را به‌صورت فایل‌های NumPy (.npy) ذخیره می‌کند.

###  Configure 3DRadius_lm.py To Generate Radius Map


*  8: linemod_cls_names to = `['01','02','04','05','06','08','09','10','11','12','13','14','15']`
*  16: linemod_path = `"/content/dataset/linemod/Linemod_preprocessed/data/"`
*  17: original_linemod_path = `"/content/dataset/linemod/Linemod_preprocessed/data/`
*   52: for class_name in tqdm(linemod_cls_names, desc="Classes"):
*   130: pcd_load = o3d.io.read_point_cloud(linemod_path+class_name+`"/mesh.ply"`)
*  142: for i, keypoint in enumerate(keypoints[:9], `start=1`):
*  160: dataDict = rootDict + "`depth/`"
*  167: mask = np.asarray(Image.open(linemod_path+class_name+"/mask/"+os.path.splitext(filename)[0][5:].`zfill(6)`+".png"), dtype=int)
*  174: RT = np.load(linemod_path + class_name + "/pose/pose" + os.path.splitext(filename)[0][9:].`zfill(6)` + ".npy")
*  176: Comment This Line: `print(linemod_pose(rootDict, os.path.splitext(filename)`
*   Add ProgressBar:
.   Add ``` from tqdm import tqdm  ``` at top

 .Modify
```
6: from numba import jit, prange
7: from numba import jit, prange
8: from tqdm import tqdm
```

```
50 after main: for class_name in linemod_cls_names:

```















### **Generate Radius Map**

In [ ]:
!python3 /content/rcvpose/3DRadius_lm.py

Processing Classes:   0% 0/13 [00:00<?, ?it/s]Class 01
Processing Classes:   0% 0/13 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "/content/rcvpose/3DRadius_lm.py", line 78, in <module>
    xyz, ys, xs = rgbd_to_point_cloud(linemod_K, realdepth)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/rcvpose/3DRadius_lm.py", line 28, in rgbd_to_point_cloud
    vs, us = depth.nonzero()
             ^^^^^^^^^^^^^^^
KeyboardInterrupt
^C


### **Train Model**

### Split Data: %70: Train - %20 Validation - %10 Test

In [ ]:
#Split RGB Files to Train Validate Test
import os
import glob
import yaml
import random

# ==== CONFIGURATION ====
# Base directory containing class subfolders
base_dir = "/content/dataset/linemod/Linemod_preprocessed/data"
# List of class identifiers to process
classes = ["01","02","04","05","06","08","09","10","11","12","13","14","15"]
# Fixed seed for reproducibility in splitting
random.seed(42)

for cls in classes:
    print(f"\n--- Splitting RGB frames for class {cls} ---")

    # 1) Gather all RGB image indices (filenames without extension)
    rgb_dir = os.path.join(base_dir, cls, "rgb")
    rgb_paths = sorted(glob.glob(os.path.join(rgb_dir, "*.png")))
    rgb_idx = [os.path.splitext(os.path.basename(p))[0] for p in rgb_paths]

    # 2) Load GT keys from gt.yml, zero-pad them to six digits
    gt_path = os.path.join(base_dir, cls, "gt.yml")
    if not os.path.isfile(gt_path):
        print(f"WARNING: gt.yml not found for class {cls}, skipping.")
        continue

    with open(gt_path, "r") as f:
        gt = yaml.safe_load(f)
    gt_keys = {f"{int(k):06d}" for k in gt.keys()}

    # 3) Keep only indices present in both RGB and GT
    valid_idx = [i for i in rgb_idx if i in gt_keys]
    if not valid_idx:
        print(f"WARNING: No valid frames for class {cls}, skipping.")
        continue

    # 4) Shuffle and split 70% train / 20% val / 10% test
    random.shuffle(valid_idx)
    n = len(valid_idx)
    cut1 = int(0.7 * n)
    cut2 = int(0.9 * n)
    train_idx = valid_idx[:cut1]
    val_idx   = valid_idx[cut1:cut2]
    test_idx  = valid_idx[cut2:]

    # 5) Write splits to text files under a new "Split" folder
    split_dir = os.path.join(base_dir, cls, "Split")
    os.makedirs(split_dir, exist_ok=True)
    with open(os.path.join(split_dir, "train.txt"), "w") as f:
        f.write("\n".join(train_idx))
    with open(os.path.join(split_dir, "val.txt"), "w") as f:
        f.write("\n".join(val_idx))
    with open(os.path.join(split_dir, "test.txt"), "w") as f:
        f.write("\n".join(test_idx))

    print(f"✅ Class {cls}: train={len(train_idx)}, val={len(val_idx)}, test={len(test_idx)}")

print("\nAll classes processed successfully.")



--- Splitting RGB frames for class 01 ---
✅ Class 01: train=865, val=247, test=124

--- Splitting RGB frames for class 02 ---
✅ Class 02: train=849, val=243, test=122

--- Splitting RGB frames for class 04 ---
✅ Class 04: train=840, val=240, test=121

--- Splitting RGB frames for class 05 ---
✅ Class 05: train=837, val=239, test=120

--- Splitting RGB frames for class 06 ---
✅ Class 06: train=825, val=236, test=118

--- Splitting RGB frames for class 08 ---
✅ Class 08: train=831, val=238, test=119

--- Splitting RGB frames for class 09 ---
✅ Class 09: train=877, val=251, test=126

--- Splitting RGB frames for class 10 ---
✅ Class 10: train=877, val=250, test=126

--- Splitting RGB frames for class 11 ---
✅ Class 11: train=854, val=244, test=122

--- Splitting RGB frames for class 12 ---
✅ Class 12: train=865, val=248, test=124

--- Splitting RGB frames for class 13 ---
✅ Class 13: train=806, val=230, test=116

--- Splitting RGB frames for class 14 ---
✅ Class 14: train=858, val=246, t

In [ ]:
# @title Normalize and overwrite dataset files in-place
import os
import numpy as np
from PIL import Image

# Parameters
ROOT        = "/content/dataset/linemod/Linemod_preprocessed/data"
CLASSES     = sorted([d for d in os.listdir(ROOT) if os.path.isdir(os.path.join(ROOT, d))])
OUT_PTS     = [f"Out_pt{i}_dm" for i in range(1,10)]
MEAN_RGB    = np.array([0.485, 0.456, 0.406], dtype=np.float32)
STD_RGB     = np.array([0.229, 0.224, 0.225], dtype=np.float32)
DEPTH_MAX   = 10.0

def read_depth_dpt(path):
    with open(path, "rb") as f:
        h, w = np.fromfile(f, dtype=np.uint32, count=2)
        data = np.fromfile(f, dtype=np.uint16, count=h*w)
    return data.reshape(h, w).astype(np.float32)

for cls in CLASSES:
    cls_dir = os.path.join(ROOT, cls)
    print(f"Processing class {cls}…")
    # ---- normalize Out_ptX_dm/*.npy ----
    for out_dir in OUT_PTS:
        full_out = os.path.join(cls_dir, out_dir)
        if not os.path.isdir(full_out):
            continue
        for fname in os.listdir(full_out):
            if not fname.endswith(".npy"):
                continue
            path = os.path.join(full_out, fname)
            arr  = np.load(path).astype(np.float32)
            m = arr.max() if arr.max()>0 else 1.0
            arr_norm = arr / m
            np.save(path, arr_norm)
    # ---- normalize rgb, depth, mask, pose ----
    # find all image ids from Split/train.txt
    split = os.path.join(cls_dir, "Split", "train.txt")
    if not os.path.isfile(split):
        split = os.path.join(cls_dir, "Split", "val.txt")
    ids = [l.strip() for l in open(split).readlines()]
    for img_id in ids:
        idx = int(img_id)
        # rgb
        rgb_p  = os.path.join(cls_dir, "rgb",   f"{idx:06d}.png")
        im     = np.asarray(Image.open(rgb_p).convert("RGB"), dtype=np.float32) / 255.0
        im     = (im - MEAN_RGB[None,None,:]) / STD_RGB[None,None,:]
        np.save(rgb_p.replace(".png", ".npy"), im)
        # depth
        dp_p   = os.path.join(cls_dir, "depth", f"{idx:06d}.dpt")
        dp     = read_depth_dpt(dp_p)
        dp     = np.clip(dp, 0, DEPTH_MAX) / DEPTH_MAX
        np.save(dp_p.replace(".dpt", ".npy"), dp)
        # mask
        ms_p   = os.path.join(cls_dir, "mask",  f"{idx:06d}.png")
        ms     = np.asarray(Image.open(ms_p).convert("L"), dtype=np.uint8)
        ms_bin = (ms>0).astype(np.float32)
        np.save(ms_p.replace(".png", ".npy"), ms_bin)
        # pose
        p_p    = os.path.join(cls_dir, "pose",  f"pose{idx:06d}.npy")
        pose   = np.load(p_p).astype(np.float32)
        # optionally normalize translation by 1000 (meters→mm)
        pose[:3,3] /= 1000.0
        np.save(p_p, pose)

print("Normalization complete. Overwritten .npy files alongside originals.")


Processing class 01…


KeyboardInterrupt: 

### Start Training After Modify These Lines at rmap_dataset.py

*   32: self._imgpath     = os.path.join(self.root,'data', self.obj_name, 'rgb', '%06d.png')
*   34: self._depthpath   = os.path.join(self.root,'data', self.obj_name, 'depth', '%06d.dpt')
*   35: self._maskpath    = os.path.join(self.root,'data', self.obj_name, 'mask', '%06d.png')
*   36: self._gtposepath  = os.path.join(self.root,'data', self.obj_name, 'pose', 'pose%06d.npy')
*   37: self._imgsetpath  = os.path.join(self.root,'data', self.obj_name, 'Split', '%s.txt')
*   41: cad_model_mm = o3d.io.read_point_cloud(os.path.join(self.root, 'data', self.obj_name, 'mesh.ply'))
*   42 - 43: After cad_model_points_m -> kpt_file = os.path.join(self.root, 'data', self.obj_name, 'Outside9.npy')
* 50: After cad_model_points_m -> kpt_file = os.path.join(self.root, 'data', self.obj_name, 'Outside9.npy')
*   After kpt_file ->

```
if os.path.isfile(os.path.join(self.root, self.obj_name,'Outside9.npy')):
      self.kpt = np.load(os.path.join(self.root,self.obj_name,'Outside9.npy'))
else:
 (Add)->np.save(os.path.join(self.root,"data", self.obj_name,'Outside9.npy'), self.kpt)
```


*   77: depth = read_depth(self._depthpath % int(img_id))






### rmap_dataset.py:


*   76: depth  = read_depth(self._depthpath  % int(img_id))
*   77: mask   = np.asarray(Image.open(self._maskpath % int(img_id)), type=int)[:, :, 0]
*   78: gtpose = np.load(self._gtposepath % int(img_id))
*   79: img    = Image.open(self._imgpath    % int(img_id)).convert('RGB')

            
            
            


In [ ]:
!python /content/rcvpose/main.py \
--mode train \
--class_name 01 \
--kpt_num 7 \
--root_dataset /content/dataset/linemod/Linemod_preprocessed \
--batch_size 16 \
--initial_lr 1e-4
# 9 Keypoints from (0 - 8) + 1 Core = 7

Output logs:  logs/lm/01Kp7
No kpt file found, generating kpts...
No kpt file found, generating kpts...
Using 1 GPU
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.0001
    maximize: False
    weight_decay: 0
)
Train epoch=0: 100%|████████████████████████████| 16/16 [00:11<00:00,  1.41it/s]

Train epoch=1: 100%|████████████████████████████| 16/16 [00:11<00:00,  1.44it/s]

Train:   0%|                              | 1/43750 [00:45<557:41:02, 45.89s/it]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py", line 708, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py", line 1458, in _next_data
    idx, data = self._get_data()
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/t

In [ ]:
#Backup
!cp -r /content/drive/MyDrive/ColabNotebooks/MLDL/PreProcessedData/LINEMOD/01 /content/drive/MyDrive/ColabNotebooks/MLDL/PreProcessedData

^C


In [ ]:
#Restore
!cp -r "/content/drive/MyDrive/ColabNotebooks/MLDL/PoseEstimation Backup/1 - Backup/rcvpose" /content

^C


In [3]:
#Config Git
!git config --global user.email "sina.ghiabi1@gmail.com"
!git config --global user.name "sina-ghiabi"

In [4]:
!git clone https://github.com/mldl-team/6D-pose-estimation.git


Cloning into '6D-pose-estimation'...
remote: Enumerating objects: 129, done.
remote: Total 129 (delta 0), reused 0 (delta 0), pack-reused 129 (from 1)
Receiving objects: 100% (129/129), 156.07 MiB | 55.26 MiB/s, done.
Resolving deltas: 100% (24/24), done.


In [5]:
%cd 6D-pose-estimation
!cp -r /content/drive/MyDrive/ColabNotebooks/MLDL/PreProcessedData/LINEMOD/01 /content/dataset/linemod/Linemod_preprocessed

/content/6D-pose-estimation
